name: Actions Docker Manual Sync CNB

on:
  workflow_dispatch:
    inputs:
      image:
        description: 选择要同步的镜像
        required: true
        type: choice
        options:
          - alpine
          - mlikiowa/napcat-docker
          - 3wlh/photopea

      platform:
        description: 选择要同步的目标架构
        required: true
        default: "all"
        type: choice
        options:
          - all
          - linux/amd64,linux/arm64
          - linux/amd64
          - linux/arm64

jobs:
  docker-sync:
    uses: ./.github/workflows/Call_Docker-Sync-CNB.yml
    secrets: inherit
    with:
      image: ${{ inputs.image }}
      platform: ${{ inputs.platform }}
