name: Call Docker Push

on:
  workflow_call:
    inputs:
      platform:
        type: string
      image:
        type: string
      repo:
        type: string

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./${{ inputs.image }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Initial
        run: |
          sudo timedatectl set-timezone "${TZ}"
          echo "name=$(echo ${{ inputs.image }} | tr 'A-Z' 'a-z')" >> $GITHUB_ENV

      - name: Login to Docker Hub
        if: ${{ inputs.repo == 'docker-hub' || inputs.repo == 'all' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to CNB
        if: ${{ inputs.repo == 'docker-cnb' || inputs.repo == 'all' }}
        run: |
          docker login -u cnb -p ${{ secrets.CNB_TOKEN }} docker.cnb.cool

      - name: Buildx and Docker image push to Docker Hub
        if: ${{ inputs.repo == 'docker-hub' || inputs.repo == 'all' }}
        env:
          DOCKER_REPO: 3wlh/${{ env.name }}
        run: |
          docker buildx build \
            --output "type=image,push=true" \
            --platform ${{ inputs.platform }} \
            --tag ${DOCKER_REPO}:latest \
            --file ./Dockerfile \
            .

      - name: Buildx and Docker image push to CNB
        if: ${{ inputs.repo == 'docker-cnb' || inputs.repo == 'all' }}
        env:
          DOCKER_REPO: docker.cnb.cool/3wlh/docker-repo/${{ env.name }}
        run: |
          docker buildx build \
            --output "type=image,push=true" \
            --platform ${{ inputs.platform }} \
            --tag ${DOCKER_REPO}:latest \
            --file ./Dockerfile \
            .

      - name: Docker Hub logout
        if: always()
        run: docker logout

      - name: CNB logout
        if: always()
        run: docker logout docker.cnb.cool
