name: Actions Docker

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      method:
        description: 选择要执行的操作类型
        required: true
        default: "release"
        type: choice
        options:
          - push
          - Release
          - Remove

      image:
        description: 选择要编译的镜像模块
        required: false
        default: "all"
        type: choice
        options:
          - all
          - NapCat_api
          - NapCat_Service
          - PaddleOCR
          - Photopea
          - Skopeo

      platform:
        description: 选择要编译的目标架构
        required: true
        default: "linux/amd64,linux/arm64"
        type: choice
        options:
          - linux/amd64,linux/arm64
          - linux/amd64
          - linux/arm64

      repo:
        description: 选择镜像推送的目标仓库
        required: true
        default: "all"
        type: choice
        options:
          - all
          - docker-hub
          - docker-cnb

jobs:
  docker-push:
    if: ${{ inputs.method == 'push' }}
    uses: ./.github/workflows/Call_Docker-push.yml
    secrets: inherit
    with:
      image: ${{ inputs.image }}
      platform: ${{ inputs.platform }}
      repo: ${{ inputs.repo }}

  docker-release:
    if: ${{ inputs.method == 'Release' }}
    uses: ./.github/workflows/Call_Docker-release.yml
    secrets: inherit
    with:
      image: ${{ inputs.image }}
      platform: ${{ inputs.platform }}

  docker-delete:
    if: ${{ inputs.method == 'Remove' }}
    uses: ./.github/workflows/Call_Docker-remove.yml
    secrets: inherit
    with:
      repo_name: ${{ inputs.image }}
