name: Build and Image

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: "SSH connection to Actions"
        required: false
        default: false
        type: boolean
      
      name:
        description: "Select the Source"
        required: false
        default: "all"
        type: choice
        options:
          - all
          - NapCat

          
env:
  Dockerfile: ${{ inputs.name }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    steps:
      - name: Prepare
        run: |
          platform=${{ matrix.platform }}
          echo "Arch=$(echo ${platform} | tr -d "linux/")" >> $GITHUB_ENV
          echo "Name=$(echo ${{ inputs.name }} | tr 'A-Z' 'a-z')" >> $GITHUB_ENV
          
      - name: Set up the working directory
        run: |
          working-directory: ./${{ inputs.name }}/${{ env.Arch }}
            
      - name: Check out code
        uses: actions/checkout@v2    
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build multi-arch Docker image
        run: | 
          ls
          echo ${{ env.Arch }}
          echo ${{ env.Name }}
          # cd "${{ inputs.name }}/${{ env.Arch }}"
          docker buildx build --platform ${{ matrix.platform }} -t ${{ env.Name }}:latest .
          
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: ${{ matrix.platform }}
          push: true
          tags: ${{ env.Name }}:latest
          