name: Build and Image Rmi

on:
  repository_dispatch:
  workflow_dispatch:      
    inputs:    
      image:
        description: "Select the Image"
        required: false
        default: "all"
        type: choice
        options:
          - all
          - NapCat_api
          - NapCat_Service
          - PaddleOCR
          
env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./${{ inputs.image }}
    steps:       
      - name: Check out code
        uses: actions/checkout@v4    
        
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Initial
        run: |
          sudo timedatectl set-timezone "${TZ}"
          echo "Name=$(echo ${{ inputs.image }} | tr 'A-Z' 'a-z')" >> $GITHUB_ENV
      
      - name: Delete and Docker.hub image
        env:
          DOCKER_REPO: 3wlh/${{ env.Name }}
        run: |
          docker image delete ${{ env.Name }}
            .
            
      - name: Docker Hub logout
        if: always()
        run: docker logout 