name: Build and Image

on:
  repository_dispatch:
  workflow_dispatch:      
    inputs:  
      name:
        description: "Select the Source"
        required: false
        default: "all"
        type: choice
        options:
          - all
          - NapCat_api

env:
  Dockerfile: ${{ inputs.name }}

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./${{ inputs.name }}
    steps:       
      - name: Check out code
        uses: actions/checkout@v4    
        
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Initial
        run: |
          sudo timedatectl set-timezone "${TZ}"
          echo "Name=$(echo ${{ inputs.name }} | tr 'A-Z' 'a-z')" >> $GITHUB_ENV
      
      - name: Buildx and Docker image push
        env:
          DOCKER_REPO: 3wlh/${{ env.Name }}
        run: |
          # cd ${{ inputs.name }}
          TAG=$(date "+%Y.%m.%d_%H%M%S")
          docker buildx build \
            --output "type=image,push=true" \
            --platform linux/amd64,linux/arm64 \
            # --tag ${DOCKER_REPO}:$TAG \
            --tag ${DOCKER_REPO}:latest \
            --file ./Dockerfile \
            .
            
      - name: Docker Hub logout
        if: always()
        run: docker logout          