name: Build and Image

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: "SSH connection to Actions"
        required: false
        default: false
        type: boolean
      
      name:
        description: "Select the Source"
        required: false
        default: "all"
        type: choice
        options:
          - all
          - NapCat
          - wxpusher
          
env:
  Dockerfile: ${{ inputs.name }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: linux/amd64
          - arch: linux/arm64
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build multi-arch Docker image
        run: |
          Arch=$(echo ${str} | tr -d "linux/")
          cd "${{ inputs.name }}/${Arch}"
          docker buildx build --platform ${{ matrix.arch }} -t ${{ inputs.name }}:latest .
          
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: ${{ matrix.arch }}
          push: true
          tags: 3wlh/${{ inputs.Source_name }}:latest