name: Build and Image
on:
  repository_dispatch:
  workflow_dispatch:      
    inputs:
      platform:
        description: "Select the platform"
        required: false
        default: "linux/amd64,linux/arm64"
        type: choice
        options:
          - linux/amd64,linux/arm64
          - linux/amd64
          - linux/arm64
          
      image:
        description: "Select the Image"
        required: false
        default: "all"
        type: choice
        options:
          - all
          - NapCat_api
          - PaddleOCR
          
env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./${{ inputs.image }}
    steps:       
      - name: Check out code
        uses: actions/checkout@v4    
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Initial
        run: |
          sudo timedatectl set-timezone "${TZ}"
          echo "Name=$(echo ${{ inputs.image }} | tr 'A-Z' 'a-z')" >> $GITHUB_ENV

      - name: docker images
        run: |
          docker images